// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgrbqlyafvwdntmrqrvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhncmJxbHlhZnZ3ZG50bXJxcnZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNDQ0NzUsImV4cCI6MjA2MDkyMDQ3NX0.4iu8OVYRAmx-4SoCfQeyJAfhUoDFMFD15t_rBB3h6yI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);